require 'rake/testtask'


Rake::TestTask.new do |t|
  t.libs << 'tests'
  t.test_files = FileList['tests/test*.rb']
  # t.test_files = FileList['tests/test_single.rb']
  t.verbose = true
end


task :default => [:run]


task :run do
  # ruby './bin/temp_class.rb'
  ruby './bin/main_class.rb'
end

task :tag do
  ruby './bin/api_source_tagger.rb'
end


task :stat do
    ruby "./bin/card_counter.rb"  
end


task :upload do
    ruby "./bin/upload.rb"  
end
